### PR TITLE
ENTESB-13948: adding the ability for override data wrapper which is p…

### PR DESCRIPTION
**Pull request by rareddy**
…rovided in different DDL statement than create server

### CODE REVIEW

**Comment by rareddy** [comment]
That is TYPE on the CREATE SERVER right? Some examples and documents show that then we can take it out

**Comment by shawkins** [comment]
No on a foreign data wrapper.  The regex here expects it to specify TYPE.  I'm saying that the current grammar accepts both type and handler: http://teiid.github.io/teiid-documents/master/content/reference/r_bnf-for-sql-grammar.html#createDataWrapper

**Comment by rareddy** [comment]
Ok, I will log an issue on Teiid

**Comment by shawkins** [comment]
Captured as https://issues.redhat.com/browse/TEIID-5967

**Pull request merged**
