### PR TITLE
updated metrics and service monitoring logic generated by operator-sd…

### PR DESCRIPTION
**Pull request by akoserwal**
Updated metrics and monitoring logic generated by operator-sdk v15+ version.

### CODE REVIEW

**Comment by rareddy** [comment]
Do I need to update the operator-sdk for this?

**Comment by akoserwal** [comment]
Not required it is available in 0.15.1 as well.

**Comment by shawkins** [comment]
After I apply these I see an error during make build:

build github.com/operator-framework/operator-sdk/pkg/kube-metrics: cannot load github.com/operator-framework/operator-sdk/pkg/kube-metrics: open /home/shawkins/workspaces/teiidsb/teiid-operator/vendor/github.com/operator-framework/operator-sdk/pkg/kube-metrics: no such file or directory

I had to run $go mod vendor

That makes quite a few updates under vendor and a change to go.sum.  @rareddy do you want that all checked in as well?

**Comment by rareddy** [comment]
I will fix this as part of this issue. Give me few minutes

**Comment by rareddy** [comment]
Ok, done. You can update now. Thanks

**Comment by shawkins** [comment]
The next issue is that the operator pod log is filled with errors.  At a rate of 2 per second we see:

E0402 18:19:13.457042       1 reflector.go:123] github.com/operator-framework/operator-sdk/pkg/kube-metrics/store.go:65: Failed to list *unstructured.Unstructured: pods "proxy" not found
E0402 18:19:13.610239       1 reflector.go:123] github.com/operator-framework/operator-sdk/pkg/kube-metrics/store.go:65: Failed to list *unstructured.Unstructured: deploymentconfigs.apps.openshift.io "log" not found
E0402 18:19:14.461453       1 reflector.go:123] github.com/operator-framework/operator-sdk/pkg/kube-metrics/store.go:65: Failed to list *unstructured.Unstructured: pods "proxy" not found
E0402 18:19:14.625670       1 reflector.go:123] github.com/operator-framework/operator-sdk/pkg/kube-metrics/store.go:65: Failed to list *unstructured.Unstructured: deploymentconfigs.apps.openshift.io "log" not found

**Comment by rareddy** [comment]
This seems to be more problematic, I fixed all but one error, I am looking for a solution. Meanwhile, if you want you can just install the OPerator from Operator hub and use that

**Comment by rareddy** [comment]
@akoserwal I updated many permissions but I am still seeing 

```
Failed to watch *unstructured.Unstructured: the server does not allow this method on the requested resource
Failed to list *unstructured.Unstructured: the server could not find the requested resource
```

do you know what permission this needs, btw my operator is not a cluster-wide operator, it is namespace operator.

**Comment by akoserwal** [comment]
@rareddy: This might be the case: https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#default-metrics-exported-with-3rd-party-resource

```The kubemetrics.GenerateAndServeCRMetrics function requires an RBAC rule to list all GroupVersionKinds in the list of watched namespaces, so you might need to filter the kinds returned by k8sutil.GetGVKsFromAddToScheme more stringently to avoid authorization errors such as Failed to list *unstructured.Unstructured. You may also need to add a rule to LIST your third party API schemas and their dependent schemas not registered with the manager.
```

**Pull request merged**
