### PR TITLE
Pre-link image pull secret into SA

### PR DESCRIPTION
**Pull request by asmigala**

### CODE REVIEW

**Comment by rareddy** [comment]
I have not found any references to this anywhere, so I am guessing this is not needed if you are working with say official OpenShift drops, only in minishift or private cluster this would needed. Also this is not the whole story, the getting of the secret and linking *are* the main parts that you show in your example. so, let's leave those concerns outside for now.

**Comment by asmigala** [comment]
@rareddy here's the reference: https://docs.openshift.com/container-platform/3.11/dev_guide/managing_images.html#using-image-pull-secrets

`oc secret link <serviceaccount> <secretname> --for=pull` does exactly this.

**Comment by rareddy** [comment]
Yes, I saw the above. I mean in Syndesis I did not find anything similar. So, are you thinking user will have the knowledge to pull in the secret but since we need a way assosiate with SA we need this change, then I can how this can be useful.

**Comment by asmigala** [comment]
https://github.com/syndesisio/fuse-online-install/blob/master/libs/openshift_functions.sh#L219
https://github.com/syndesisio/fuse-online-install/blob/master/install_ocp.sh#L342

And also the syndesis operator will automatically link the `syndesis-pull-secret` into its service account:
https://github.com/syndesisio/syndesis/blob/master/install/operator/pkg/syndesis/action/install.go#L38
https://github.com/syndesisio/syndesis/blob/master/install/operator/pkg/syndesis/action/install.go#L482

**Comment by rareddy** [comment]
how about if I add this `install-operator.sh` in `openshift-examples` along with PR?

```
#!/bin/bash

set -eu
set -o pipefail

export OP_ROOT=https://raw.githubusercontent.com/teiid/teiid-operator/master/deploy
export REGISTRY=registry.redhat.io

create_secret_if_not_present() {
  if $(check_resource secret dv-pull-secret) ; then
    echo "pull secret 'dv-pull-secret' present, skipping creation ..."
  else
    echo "pull secret 'dv-pull-secret' is missing, creating ..."
    echo "enter username for ${REGISTRY} and press [ENTER]: "
    read username
    echo "enter password for ${REGISTRY} and press [ENTER]: "
    read -s password
    local result=$(oc create secret docker-registry dv-pull-secret --docker-server=${REGISTRY} --docker-username=$username --docker-password=$password)
    check_error $result
  fi
}

# Check if a resource exist in OCP
check_resource() {
  local kind=$1
  local name=$2
  oc get $kind $name -o name >/dev/null 2>&1
  if [ $? != 0 ]; then
    echo "false"
  else
    echo "true"
  fi
}

create_secret_if_not_present

oc create -f $OP_ROOT/crds/virtualdatabase.crd.yaml
oc create -f $OP_ROOT/service_account.yaml
oc create -f $OP_ROOT/role.yaml
oc create -f $OP_ROOT/role_binding.yaml
oc create -f $OP_ROOT/operator.yaml
```

**Comment by asmigala** [comment]
@rareddy lgtm

**Pull request merged**
