### PR TITLE
Add ConsoleLink Creation, Update Util, and Add Unit Test Cases

### PR DESCRIPTION
**Pull request by rashelrr**
Signed-off-by: Rashel Rojas <rarojas@redhat.com>

Added ConsoleLink creation and updated utils. 
Added unit test cases.

Line 56 in /deploy/olm-catalog/teiid/0.3.0/teiid.v0.3.0.clusterserviceversion.yaml file should be modified (as shown in commit) to "name: teiid.v0.3.0" for the operator-courier to work. This should then match Line 2 in teiid.package.yaml.

### CODE REVIEW

**Comment by rareddy** [comment]
is this good to be pull in, or you still working on it? When ready let me know removing by draft state I will test and merge this PR

**Comment by myeung18** [comment]
> is this good to be pull in, or you still working on it? When ready let me know removing by draft state I will test and merge this PR

Sure, will do, thank you.

**Comment by rashelrr** [comment]
> is this good to be pull in, or you still working on it? When ready let me know removing by draft state I will test and merge this PR

This is ready to pull in.

**Comment by rareddy** [comment]
great, I will take a look

**Comment by rareddy** [comment]
Thank you for your contribution.

**Pull request merged**
